apiVersion: v2
name: fer-service
description: A Helm chart for Facial Expression Recognition Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - facial-expression-recognition
  - machine-learning
  - fastapi
home: https://github.com/yourusername/fer-project
sources:
  - https://github.com/yourusername/fer-project
maintainers:
  - name: Your Name
    email: your.email@example.com
