apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fer-model-pvc
  namespace: fer-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
